### ISSUE TITLE
Become an official Mozilla Contributor

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#119]
@jsub1 @cbohl @timchoh585 and others on the @MozillaHive/ridew-me-volunteer-contributors team interested...

I want to work towards recognizing you as official Mozilla contributors. It doesn’t come with big bucks, we are a non-profit, volunteer organization, but it still means something significant in the developer community!

* To get the Mozilla contributor thing going, please visit this page and follow instructions: http://mozilla.org/contribute
* once you have a Mozillians account profile (will make sense soon) let me know so I can “vouch” for you and make it official!

**Comment by kyaroch** [comment]
I’ve created a profile: https://mozillians.org/en-US/u/kjyaroch/ <https://mozillians.org/en-US/u/kjyaroch/>

-Kevin

**Comment by timchoh585** [comment]
*https://mozillians.org/en-US/u/timchoh585/
<https://mozillians.org/en-US/u/timchoh585/> *
*thats my url for the mozillian thing*
ᐧ

[image: clubspark.org] <http://clubspark.org/>

*Tim Choh */ Co-Founder and Project Manager
tchoh2@uic.edu, timchoh@gmail.com

Github <https://github.com/timchoh585> LinkedIn
<http://www.linkedin.com/in/timchoh585>

On Tue, Jul 7, 2015 at 9:22 PM, Robert B. Friedman <notifications@github.com

**Comment by jsub1** [comment]
https://mozillians.org/en-US/u/subbaraojeffrey/ for me

**Comment by cbohl** [comment]
https://mozillians.org/en-US/u/cbohl/ for me!
