### ISSUE TITLE
Creation of test suite

### ISSUE THREAD

**Issue by kyaroch** [MozillaHive/HiveCHI-rwm#132]
Given the increasing number of collaborators, it could be useful to create a test suite (rspec?) so that we can be sure we're not breaking anything when we commit changes.

**Comment by kyaroch** [comment]
Here's a guide explaining how to prevent Twilio from sending real texts during tests: http://www.sitepoint.com/adding-sms-capabilities-to-your-rails-app/

**Comment by kyaroch** [comment]
I need to learn RSpec anyway, so I'll start working on user model and request specs.

**Comment by kyaroch** [comment]
I have an initial user spec set up, but we should merge the consolidate-controllers pull request first.

**Comment by kyaroch** [comment]
Installed RSpec and wrote up a user model spec. If anyone wants to write more specs, please do, but let me know so we can coordinate.

**Comment by cbohl** [comment]
We have a test suite!!!
