### ISSUE TITLE
Standardize Postgres environment

### ISSUE THREAD

**Issue by paul-k-me** [MozillaHive/HiveCHI-rwm#167]
There have been issues with individual developers in setting up their own local environments.  We need assistance from @kyaroch to clarify what is going on.

**Comment by kyaroch** [comment]
I will write up a post on Slack explaining how to do this. (Initially, whatever steps I provide may not work for everyone, but let me know if you have problems and I'll edit it to address those problems.)

**Comment by kyaroch** [comment]
The above post was written and is pinned in #devs.
