### ISSUE TITLE
Nonexistent phone numbers cause registration to fail without explanation

### ISSUE THREAD

**Issue by kyaroch** [MozillaHive/HiveCHI-rwm#179]
If someone enters an invalid phone number (i.e., wrong number of digits) while registering, this gets handled properly. If the user enters a phone number that _could_ be valid but actually doesn't exist – which could happen because of a typo – they just get an "error loading page" message with no explanation of what's wrong. This is because the app attempts to send a text while saving the new user, and Twilio raises an exception.

We can solve this problem in the following ways:

1. Use Twilio Carrier Lookup to make sure the number is real before texting it. Note: each lookup costs half a cent.
2. Catch the exception and handle this error like a validation failure. (Not sure how best to do this, but presumably it can be done.)
3. Do nothing for now.

**Comment by omnignorant** [comment]
4. add helper text to note that registration cannot be completed without a valid phone number.
