### ISSUE TITLE
Registration returns error even if everything is OK

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#181]
![screenshot 2015-08-01 22 34 54](https://cloud.githubusercontent.com/assets/6335874/9024602/bf8909be-389d-11e5-9851-571d3622060d.png)

**Comment by kyaroch** [comment]
Hmm. Can someone who has access to the server logs check to see what's going on? The current master works for me if I run it locally, but I was able to reproduce this on Heroku.

Also, @omnignorant – did registration fail completely, or did it create the user (and send the email, etc.) but fail to redirect you?

**Comment by omnignorant** [comment]
no email or phone confirmations sent and I am unable to login with that username. Kevin, do you have a heroku account? we can add you as an admin for the app.

**Comment by kyaroch** [comment]
Yes; it's kjyaroch@gmail.com

**Comment by kyaroch** [comment]
That problem was caused by environment variables not being set up quite right, which I fixed - but now there's another problem. Registration still fails because the app can't send the verification email. It throws Errno::ECONNREFUSED (Connection refused - connect(2)).

**Comment by kyaroch** [comment]
On further investigation, we can't send email from Heroku without installing an add-on. It looks like we can use SendGrid for free, but we'll need to set this up.
