### ISSUE TITLE
Add a "share" button to event page and/or nudge a non-registered phone/email.

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#198]
To help spread the word and increase users, we should be nudging/sharing outside of registered users too. So either a) we can add a share button or something to email, sms, facebook, etc. for events AND/OR we can add an option to nudge someone by entering their phone number or email addy, rather than just selecting from a user list.

**Comment by paul-k-me** [comment]
@omnignorant , how do you reconcile this with the (at least initial) limitation to only accept as users kids who are from CPS?  That can't be checked before sending out a "share" to a phone # or FB account...  Thoughts?
