### ISSUE TITLE
Login/Logout pages are not formatted the same way

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#203]
This is totally minor, but the logout button redirects to a page "../logout" that isn't formatted like the "../login" page.

**Comment by kyaroch** [comment]
This is happening because the logout redirect doesn't load login.css

**Comment by paul-k-me** [comment]
This seems related to pre-existing issue #162 ; there shouldn't be a logout page at all, and when you log out you land on the login page.
