### ISSUE TITLE
[Trello New Issue] registration email in ride6 has validation link that points to localhost:3000 instead of demo.ridewit.me

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#294]
<b>Robert Friedman</b> added the card <a href="http://ift.tt/1DtBjTo">registration email in ride6 has validation link that points to localhost:3000 instead of demo.ridewit.me</a> to the <b>New Issues</b> list in the <b>Polish ride5 for CSMMF Demo</b> board at August 5, 2015 at 06:59AM<br><br><br><br><a href="http://ift.tt/1DtBjTo">View on Trello</a>

**Comment by jsub1** [comment]
That looks like ENV['HOSTNAME'] was not set correctly. @cbohl or @kyaroch should be able to fix that
