### ISSUE TITLE
[Trello New Issue] Reorder dashboard

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#296]
<b>Robert Friedman</b> added the card <a href="http://ift.tt/1KQiX1Q">Reorder dashboard</a> to the <b>New Issues</b> list in the <b>Polish ride5/6 for CSMMF Demo</b> board at August 5, 2015 at 07:17AM

1. My Events 
2. My Nudges 
3. Trending 
4. Find Events

**Comment by cbohl** [comment]
Completed by Jeff!
