### ISSUE TITLE
[Trello] Change "Edit Profile" on nav bar to just "Profile"

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#302]
<b>Robert Friedman</b> added the card <a href="http://ift.tt/1KQuIm0">#302 Change "Edit Profile" on nav bar to just "Profile"</a> to the <b>New Issues</b> list in the <b>Polish ride5/6 for CSMMF Demo</b> board at August 5, 2015 at 08:18AM<br>
Edit profile doesn't fit in mobile view.

**Comment by jsub1** [comment]
#323
