### ISSUE TITLE
[Trello] Logging in with incorrect password raises exception instead of failing because check for parent password is bugged.

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#305]
<b>Kevin Yaroch</b> added the card <a href="http://ift.tt/1E8lyfy">Logging in with incorrect password raises exception instead of failing, because check for parent password is bugged.</a> to the <b>New Issues</b> list in the <b>Polish ride6 for CSMMF Demo</b> board at August 5, 2015 at 10:46AM<br>

**Comment by kyaroch** [comment]
Resetting the database fixed this.
