### ISSUE TITLE
New users model

### ISSUE THREAD

**Issue by cbohl** [MozillaHive/HiveCHI-rwm#387]
User
-Email (string)
-Password (string)
-Phone # (string, optional)
-Timezone (string)
-accept_sms (bool)

Subclasses

Students
-username (string)
-school_id
-home_address (string, optional)
-has_many parents
-preferences (hash)
-addresses (string)
~~-can_nudge (does this belong in the preferences hash?)~~

Parents
-has_many students

Service Providers
-organization_id

Relatives Table
-student_id
-parent_id

**Comment by jsub1** [comment]
Updated to cross out can_nudge and add accept_sms for users. I think that we want to provide is the option to disable SMS messages, not really the option to prevent nudges entirely.

**Comment by cbohl** [comment]
Agreed.

**Comment by kyaroch** [comment]
I was thinking about what we discussed earlier. To recap, we plan to create a `belongs_to: profile, polymorphic: true` association for `User`, then create `StudentProfile`, `ParentProfile`, and `ServiceProviderProfile` classes with `has_one: user, as: profile`.

It seems like `User`, in this design, would handle authentication and sessions and not much else. All the other logic of our application – the associations and so forth – will vary by role. If we use the above names, we'd be typing things like `parent_profile.student_profiles`, which would get confusing. So I'm gonna suggest we do it like this:

```ruby
class User < ActiveRecord::Base
  belongs_to :role, polymorphic: true
end

class Role < ActiveRecord::Base
  self.abstract_class = true
  has_one :user, dependent: :destroy
end

class Student < Role
end

class Parent < Role
end

class ServiceProvider < Role
end
```
We could even do something like this:
```ruby
class Role < class Role < ActiveRecord::Base
  self.abstract_class = true
  has_one :user, as: :role, dependent: :destroy

  def email
     user.email
  end
end
```
Then we could mostly forget about the whole `User` model, except in the contexts where we really need it (authentication and sessions).

Does this make sense?
