### ISSUE TITLE
Complete CPS List of Schools

### ISSUE THREAD

**Issue by cbohl** [MozillaHive/HiveCHI-rwm#426]
The current list of CPS schools that users can choose from does not include all of them. The schools need to be updated in the seed file.
https://trello.com/c/deUGq22v/58-fix-the-school-list-to-include-the-most-current-list-of-cps-schools

**Comment by jbarnicle** [comment]
Is there a list of of all the schools in an excel / csv file somewhere?

**Comment by jbarnicle** [comment]
I found a list from 2013-2014.  Will start with that. 

https://data.cityofchicago.org/Education/CPS-Schools-2013-2014-Academic-Year/c7jj-qjvh
