### ISSUE TITLE
Service Provider Invalid Form Is Not Displayed

### ISSUE THREAD

**Issue by dcolemanturner** [MozillaHive/HiveCHI-rwm#466]
Device: iphone6s
URL: http://ride9.herokuapp.com/service_provider
Steps:
1.  http://ride9.herokuapp.com/register
2.  Click "Service Provider"
3.  Add some basic data and click submit

Upon submitting invalid form data, there are two issues:
1. Heading loses "selected" state
2. Student login form is displayed instead of "Service Provider"

**Comment by McEileen** [comment]
@omnignorant Hi, I just looked and saw that this issue has been fixed, please close it.  Thanks!
