### ISSUE TITLE
[Register New Account] - Service Provider 500 Error

### ISSUE THREAD

**Issue by dcolemanturner** [MozillaHive/HiveCHI-rwm#471]
Steps
1. http://ride9.herokuapp.com/register
2. Click Service Provider
3. Add valid details
4. Submit
5. Console shows 500 error for /service_provider

<img width="1611" alt="screen shot 2015-11-17 at 8 21 32 pm" src="https://cloud.githubusercontent.com/assets/254597/11230887/f87991ce-8d68-11e5-9fad-1a48b350359d.png">

**Comment by kyaroch** [comment]
This was caused by missing server-side configs. Fixed.
