### ISSUE TITLE
[Profile Edit - Service Provider] - Missing Navigation

### ISSUE THREAD

**Issue by dcolemanturner** [MozillaHive/HiveCHI-rwm#477]
Steps
1.  Log in as Service Provider
2.  Click Profile
3.  No global navigation is present.

<img width="1572" alt="screen shot 2015-11-17 at 8 40 56 pm" src="https://cloud.githubusercontent.com/assets/254597/11231202/a217548a-8d6b-11e5-9788-7ffd0ff1ffc0.png">

**Comment by kyaroch** [comment]
Fixed in #486.
