### ISSUE TITLE
[JS Error] - User is not defined

### ISSUE THREAD

**Issue by dcolemanturner** [MozillaHive/HiveCHI-rwm#482]
Steps
1.  go to http://demo.ridewit.me/register without logging in
2.  Open the console

Appears to be coming from the user variable in this function.  Only mention of "user" in public JS codebase.

var aspect_ratio = Math.min(1, $(window).height() / $(window).width() - .1);
setTimeout(function() {
    user && (directionsService = new google.maps.DirectionsService,
    calcRoute("TRANSIT", directionsService),
    calcRoute("BICYCLING", directionsService),
    calcRoute("WALKING", directionsService)),
    initialize(),
    codeAddress()
}

<img width="1096" alt="screen shot 2015-11-17 at 8 44 59 pm" src="https://cloud.githubusercontent.com/assets/254597/11231249/27951228-8d6c-11e5-9998-78fb389c2c49.png">

**Comment by omnignorant** [comment]
Javascript is generally a huge mess.
