### ISSUE TITLE
[Events] Add image upload for events

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#484]
We should create a mechanism for folks to be able to upload an image for an event they create. There are easy ways to do this using online cloud services, but I forget what they are called. I'll dig around to find out, but I think we want to enable this if possible.

Marking medium priority because I know folks are going to get turned off if it's missing.

**Comment by omnignorant** [comment]
check out: Filepicker.io

**Comment by omnignorant** [comment]
@kyaroch Also, maybe we can just make this a URL and let service providers host their own images?!?!? That would be a quick and easy fix. If we take that route, open a seperate issue.

**Comment by kyaroch** [comment]
I would suggest using Amazon S3. It'll be way cheaper (Filepicker, now Filestack, has a free limit of 250 images, which we might hit pretty quickly, and then jumps to $99/month) and better supported.

@omnignorant: Can you open an S3 account for us? It won't cost anything initially, and not much even if we eventually exceed the free tier, but I'm pretty sure you need credit card information to sign up.

**Comment by kyaroch** [comment]
Added in #519 and #520
