### ISSUE TITLE
Remove "Home Address" from Student Registration Form

### ISSUE THREAD

**Issue by cgreim** [MozillaHive/HiveCHI-rwm#493]
Currently we collect "Home Address" in the student sign up form, but we aren't doing anything with it right now. 

Ideally, we'd have a feature where you can get directions home. In the meantime, it brings up unnecessary confusion so we should remove it.

**Comment by iamstephenliu** [comment]
Completed as pull request #496.

**Comment by kyaroch** [comment]
Thanks, Stephen. Looks good.
