### ISSUE TITLE
Departure time for student displaying incorrectly 

### ISSUE THREAD

**Issue by cgreim** [MozillaHive/HiveCHI-rwm#499]
Maybe related to #498

Event is at 7PM... 

![image](https://cloud.githubusercontent.com/assets/9704003/12373967/d52061ee-bc52-11e5-914c-336640ba645a.png)

Departure time showing at 12:14AM... 

![image](https://cloud.githubusercontent.com/assets/9704003/12373970/e4e712c6-bc52-11e5-803f-854c7cc9c431.png)

**Comment by omnignorant** [comment]
This is gotta be a timezone conversion this and probably just a field in the Google Maps API. I will investigate but cannot fix myself.

**Comment by omnignorant** [comment]
Hey @kyaroch has this been addressed by the other fix to UTC times?

**Comment by kyaroch** [comment]
It has not, because the JS needs to be changed, but now that I've read through the script I can see it's just one line of code. Should have a PR up shortly.
