### ISSUE TITLE
Timing section in attendance breakdown isn't populating

### ISSUE THREAD

**Issue by cgreim** [MozillaHive/HiveCHI-rwm#503]
When viewing event as a Service Provider, the "Timing" section of the Attendance breakdown isn't populating: 

![image](https://cloud.githubusercontent.com/assets/9704003/12374204/0c3e10d4-bc5a-11e5-97c6-8f35abda2e29.png)

**Comment by cgreim** [comment]
Maybe related to #498 and #499

**Comment by kyaroch** [comment]
Fixed in PR #512. Note that this was a problem with the way the information was recorded, not the way it was displayed, so if you have old data that you entered through the form, it will still not have a defined departure time.
