### ISSUE TITLE
seed database with the new list of high schools

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#504]
We have a new list of school addresses. let's make sure we upload the CSV.

**Comment by omnignorant** [comment]
school list pulled from here: https://data.cityofchicago.org/Education/CPS-School-Locations-SY1516/2mts-wp7t

**Comment by iamstephenliu** [comment]
[CPS High Schools.csv.zip](https://github.com/MozillaHive/HiveCHI-rwm/files/93068/CPS.High.Schools.csv.zip)

**Comment by omnignorant** [comment]
PR #508
