### ISSUE TITLE
Fill my events on homepage.

### ISSUE THREAD

**Issue by jsub1** [MozillaHive/HiveCHI-rwm#54]

**Comment by omnignorant** [comment]
Hey Jeff, is this really closed?

**Comment by jsub1** [comment]
The code in the freeze2 branch populates the dashboard with events the logged in user has signed up for. The list does not currently filter out expired events, but I wasn't sure how we wanted to do that exactly.

**Comment by omnignorant** [comment]
For now, I wld say that we just disappear them. We'll need to think through how to treat recurring events before that becomes relevant. For example, a "past event" could link to recurring upcoming ones, or make them visible, etc.
