### ISSUE TITLE
Email + SMS validation

### ISSUE THREAD

**Issue by jsub1** [MozillaHive/HiveCHI-rwm#59]

**Comment by jsub1** [comment]
Should we change this to a SMS verification process?

**Comment by omnignorant** [comment]
Cld we do both? A choice? I think we shld start w/ what's easiest or most effective and then add an issue to do the other later.

If twilio integration is easy, then I wld vote SMS. But this is why push notification wld be even better.

**Comment by jsub1** [comment]
Twilio integration isn't difficult, so we could do SMS.

**Comment by omnignorant** [comment]
Changed this to be both Email and SMS validation. When a new user registers, they get an email w/a validation link, which takes them back into the app OR a validation code that they enter in the app to validate their email addy. Same for SMS.

**Comment by omnignorant** [comment]
@jsub1 I Created the Twilio account 

* Number: 844.311.RIDE
* Account Sid: ACc16c03b49a8a659668d93d4b1c2c6a04
* Auth Token: 0184338e133c2fc686a5538dcc0d930e
