### ISSUE TITLE
Add SMS Integration

### ISSUE THREAD

**Issue by omnignorant** [MozillaHive/HiveCHI-rwm#67]
We can use [Twilio](https://www.twilio.com/sms) to enable SMS instead of email for notifications and nudges (invites). It is a **very well known fact** that SMS is the single most effective way of communicating with teens and they use it extensively to communicate with each other. Way more effective than email, which is often never checked.

I'm assigning this to Jeffrey because he's been really successful with the Google Maps API and may remember this platform from Civic Hack Day 2013 (or 2014?)

**Comment by jsub1** [comment]
Right now you can nudge someone and it sends them (i.e.me) a text telling them who nudged them and what events they were nudged for

**Comment by omnignorant** [comment]
Wow, that's awesome! Using Twilio?

**Comment by jsub1** [comment]
yep

**Comment by omnignorant** [comment]
OK, then I'm going to close this issue, but I'm going to open another one to make sure we do SMS validation to confirm phone numbers are real and not spammers.
