### ISSUE TITLE
back navigation

### ISSUE THREAD

**Issue by timchoh585** [MozillaHive/HiveCHI-rwm#70]
create a back navigation button per Roberts request during the hack day.
it would be the first tab on the bottom navigation tabs on every page.

**Comment by timchoh585** [comment]
currently working on back button with JQuery right now. I am working on a local branch right now because I dont have access to internet via computer and im on my phone so cant commit to rwm repo atm.
side note, not too sure how far "back" it can go, currently trying to make it cleaner and more efficient in ways to go back.
time it takes for the back button to be able to go back to the previous page from a request is about 750 ms but it just looks like the page is loading so not too big of an issue.

**Comment by omnignorant** [comment]
Maybe just have a "dashboard" button along the bottom that just takes you all the way back to start?

**Comment by timchoh585** [comment]
currently have a back button but its for one page.  I can do both, or should I just change it to dashboard?

**Comment by omnignorant** [comment]
I think we should think about the majorly important pages in the app and create buttons for them, but you're right, for mobile experience back button wld be helpful. I guess the following three buttons come to mind for me:

1. home/dashboard
2. back button
3. profile

**Comment by timchoh585** [comment]
ok sure.  the next time i push something ill add those three things.

just to clarify though: we have bottom nav with three buttons (Home, back, prof.) and this will be on every page?

**Comment by timchoh585** [comment]
current back nav doesnt work because of something with Ruby? @jsub1   @cbohl
