### ISSUE TITLE
front end

### ISSUE THREAD

**Issue by timchoh585** [MozillaHive/HiveCHI-rwm#72]
need to redevelop a front end design.  will need to convert everything to JQuery mobile framework for ease of navigation and fixing other issues.  Dont know if this is the only solution but its a good solution for right now.

**Comment by timchoh585** [comment]
will be working on fixing the front end and making everything JQuery. making everything mobile compatible without too many differences in our pages and frameworks.

**Comment by omnignorant** [comment]
JQuery as opposed to what? How is the current front end structured?

**Comment by timchoh585** [comment]
just cleaning up the front end to make it all a similar layout. its more of a restructure of the app.
