### ISSUE TITLE
Fix "My Page" title on a few pages

### ISSUE THREAD

**Issue by paul-k-me** [MozillaHive/HiveCHI-rwm#97]
Some html pages have the Title tag set to the words "My Page".  This should be fixed and the correct page title should match the actual page name.
Examples include attendances/new.html.erb, nudges/new.html.erb, nudges/show.html.erb, and possibly others.  I recommend searching for title "My Page" across all HTML source files.

**Comment by jbundy17** [comment]
Doing file by file. Completed: attendances/new.html.erb, nudges/new.html.erb
